name = "gdalada"
description = "Low-level ADA bindings to GDAL library"
version = "0.0.1"

authors = ["Nikolay Burkov"]
maintainers = ["Nikolay Burkov <nbrk@linklevel.net>"]
maintainers-logins = ["nbrk"]
